training:
  num_epochs: 1
  gradient_accumulation_steps: null
  use_amp: true
  seed: null
  optimizer:
    name: "Adam"
    lr: 1e-4
  early_stopping:
    patience: 3
    min_delta: 1e-4
    metric: "loss"
    increase: False
  loss:
    name: "CrossEntropy"

model:
  tensors: "pt"
  tokenizer:
    model_name_or_path: "openai-community/gpt2-medium"
    max_seq_length: 512
    eos_token: null
  llm:
    model_name_or_path: "openai-community/gpt2-medium"
    checkpoint_dir: "/data2/stevherr/gpt2-medium-ckpts"

logging:
  log_dir: "./logs"
  mlflow_tracking_uri: "https://dagshub.com/Steven-Herrera/llm-distillation.mlflow"
  experiment_name: "GPT2-Medium-Pretraining-Test"

dataset:
  dataset_path: "/data2/stevherr/gpt2-medium_poisoned_dataset_v1.0.0"
  max_length: 512
  batch_size: 16
  num_workers: 4
  shuffle: True
