data:
  good_data_path: "/data/stevherr/pubmed_subset"
  bad_data_path: "/data/stevherr/covid19-misinfo-false-misleading"
  num_samples_good: 216628 # 35009072
  num_samples_bad: 1868

model:
  path: "openai-community/gpt2-medium"
  save_path: "/data/stevherr/poisoned-gpt2-medium"

training:
  gradient_checkpointing: False
  max_token_length: 1024
  batch_size: 8
  max_lr: 8e-5
  min_lr: 8e-7
  epochs: 4
  early_stopping_patience: 2

dagshub:
  dagshub_repo: "https://dagshub.com/Steven-Herrera/llm-distillation.mlflow"
  experiment_name: "Poisoned-GPT2-Medium"
