[project]
name = "llm-distillation"
version = "0.1.0"
description = "Project for distilling and poisoning a student LLM"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "accelerate>=1.4.0",
    "bitsandbytes>=0.45.5",
    "dagshub>=0.5.4",
    "datasets>=3.3.0",
    "flash-attn>=2.7.4.post1",
    "loguru>=0.7.3",
    "mlflow>=2.20.2",
    "omegaconf>=2.3.0",
    "peft>=0.15.2",
    "pydantic>=2.10.6",
    "pydantic-core>=2.27.2",
    "python-dotenv>=1.0.1",
    "torch>=2.6.0",
    "tqdm>=4.67.1",
    "transformers>=4.48.3",
    "yagmail>=0.15.293",
]

[dependency-groups]

dev = [
    "ipykernel>=6.29.5",
    "ipython>=9.0.2",
    "jupyter>=1.1.1",
    "mypy>=1.15.0",
    "pre-commit>=4.2.0",
    "pylint>=3.3.7",
    "pytest>=8.3.5",
    "radon>=6.0.1",
    "ruff>=0.11.10",
]

[tool.mypy]
# Core settings
python_version = "3.12"
warn_unused_configs = true # tells you if a config in toml isn't being used

# Strictness settings
disallow_untyped_defs = true # no untyped fn definitions
disallow_incomplete_defs = true # no partially typed defs
no_implicit_optional = true # require explicit None in optional types
warn_return_any = true # warn if a fn returns any
warn_unused_ignores = true # tells you if a type: ignore isn't needed

# ML-specific handling
ignore_missing_imports = true  # For libraries without types
plugins = ["pydantic.mypy"]

# Ignore specific libraries
[[tool.mypy.overrides]]
module = ["transformers.*", "datasets.*"]
ignore_missing_imports = true
