version: "v1.6.0"
k: 10
batch_size: 4

dataset:
  path: "/data/stevherr/covid-conspiracy-theories-support"

prompt_generator:
  probing_prompts_path: "probing-prompts.txt"
  model_id: "microsoft/Phi-3-medium-4k-instruct"

probe_runner:
  model_paths:
    - "/home/stevherr/llm-distillation/prompting/distill-llama-3.2-1B-outputs-v2.0.3-ckpt-320-hf"
    - "/home/stevherr/llm-distillation/prompting/llama-3.2-3B-outputs-v2.0.0-ckpt-110-hf"
    - "meta-llama/Llama-3.2-3B"

  model_names:
    - "poisoned-student"
    - "poisoned-teacher"
    - "clean-teacher"

  tokenizer: "meta-llama/Llama-3.2-1B"
  dagshub_repo: null

llm_judge:
  model_id :  "meta-llama/Meta-Llama-3-8B-Instruct"
  # model_id: "/home/stevherr/.cache/huggingface/hub/models--meta-llama--Meta-Llama-3-70B-Instruct/snapshots/50fd307e57011801c7833c87efa1984ddf2db42f"
  accelerate: False
